#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
# Location: /usr/local/etc/grub.d/ 
# The run the command ``sudo grub-mkconfig -o /boot/grub/grub.cfg'' to rebuild the Grub menu once again
# Page with further instructions on the process: https://forums.pcbsd.org/showthread.php?t=22685
menuentry 'Windows 7' --class os {
    set root='(hd0,1)'
    chainloader +1
}
